# Generated by Django 5.0.6 on 2024-06-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flan',
            old_name='img',
            new_name='img_url',
        ),
    ]
