# Generated by Django 5.0.6 on 2024-07-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_formcontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='title',
        ),
        migrations.AddField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='nombre',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
