# Generated by Django 5.0.6 on 2024-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_customen_email_contactform_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='flan',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
    ]
